import Head from 'next/head'
import Link from 'next/link'
import Image from "next/image"
export default function Home() {
  return (
    <div className="flex flex-col bg-mainBackground p-0">
      <Head>
        <title>SpotBlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex sticky top-0 bg-mainBackground items-center h-87">
        <h1 className='text-white'>SpotBlog Heading</h1>
      </div>
      <div className="sticky top-[87px] h-1 bg-white w-1440"></div>
      <div className="m-auto mt-10 flex flex-col items-center justify-center h-652 w-1390 border-4 rounded-3xl border-white">
        <h1 className="absolute justify-center p-0 m-0 text-center text-white">SpotBlog</h1>
        <div className="mt-400 justify-center h-3 w-1087 bg-white"></div>
      </div>
      <div className="flex items-center m-auto mt-8 justify-center w-1087 h-473 bg-slidesColor rounded-3xl">
        <h1 className='text-black'>Latest Blog</h1>
      </div>
      <div className="flex m-auto w-[1309px] h-[283px]">
        <h2 className='text-white'>RecentBlogs</h2>
        <div className="BlogSlideShow">
          {/* THis section is where the slideshows need to be and we will need to query them from GraphCMS */}
          </div>
      </div>
      <div className="min-h-screen flex-col">
        <h1 className="text-white">Hello From Index.js</h1>
        <Link href="/singleBlog">
          Go Here
        </Link>
      </div>

      <footer className="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="logo">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
