import Head from 'next/head'
import Link from 'next/link'
import Image from "next/image"
import SlideShowCard from '../components/SlideShow'
import { gql, GraphQLClient } from 'graphql-request'

const endpoint = 'https://api-us-east-1.graphcms.com/v2/cl3smw9s5ahr701z66qij4y0f/master'

const graphCMS = new GraphQLClient(endpoint)

const allEntries = gql`
{
  posts(orderBy: publishedDate_DESC) {
    title
    slug
    id
    publishedDate
    coverPhoto {
      url
    }
  }
}

`
export async function getStaticProps() {
  const { posts } = await graphCMS.request(allEntries)
  console.log(JSON.stringify(posts))
  return {
    props: {
      posts,
    },
    revalidate: 10
  }
}
export default function Home({ posts }) {

  return (
    <div className=" flex flex-col bg-mainBackground p-0">
      <Head>
        <title>SpotBlog</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex sticky top-0 bg-mainBackground items-center h-87">
        <h1 className='font-Train text-[40px] text-white'>SpotBlog</h1>
      </div>
      <div className="sticky top-[87px] h-1 bg-white w-1440"></div>
      <div className="m-auto mt-10 flex flex-col items-center justify-center h-652 w-1390 border-4 rounded-3xl border-white">
        <h1 className="font-Train text-[128px] absolute justify-center p-0 m-0 text-center text-white">SpotBlog</h1>
        <div className="mt-400 justify-center h-3 w-1087 bg-white"></div>
      </div>
      <div className="flex items-center m-auto mt-8 justify-center w-1087 h-473 bg-slidesColor rounded-3xl">
        <Link href={posts[0].slug}>
          <img className="rounded-3xl" src={posts[0].coverPhoto.url}></img>
        </Link>

      </div>
      <div className="flex flex-col mt-20 m-auto w-[1309px]">
        <h2 className='font-Train text-[64px] text-white'>RecentBlogs</h2>
        <div className="flex space-x-4 overflow-x-auto w-1309">
          {/* THis section is where the slideshows need to be and we will need to query them from GraphCMS */}
          {posts.map((post) => (
            <div className="flex-shrink-0 m-0 h-[450px] w-[500px]">
              <SlideShowCard title={post.title} slug={post.slug} key={post.id} coverPhoto={post.coverPhoto} />
            </div>

          ))}
        </div>
      </div>
      {/* <footer className="footer">
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className="logo">
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer> */}
    </div>
  )
}
